/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"

/* Other patches */
#include "alttab.h"
#include "attachx.h"
#include "autostart.h"
#include "cyclelayouts.h"
#include "dragmfact.h"
#include "fakefullscreenclient.h"
#include "fullscreen.h"
#include "mpdcontrol.h"
#include "movestack.h"
#include "pertag.h"
#include "placemouse.h"
#include "renamed_scratchpads.h"
#include "scratchpad_alt_1.h"
#include "sizehints_ruled.h"
#include "sticky.h"
#include "swallow.h"
#include "swapfocus.h"
#include "tagall.h"
#include "tagallmon.h"
#include "tagswapmon.h"
#include "vanitygaps.h"
#include "warp.h"
#include "xrdb.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

