/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"

/* Other patches */
#include "alttab.c"
#include "attachx.c"
#include "autostart.c"
#include "cyclelayouts.c"
#include "fakefullscreenclient.c"
#include "fullscreen.c"
#include "mpdcontrol.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "renamed_scratchpads.c"
#include "scratchpad_alt_1.c"
#include "sizehints_ruled.c"
#include "sticky.c"
#include "swallow.c"
#include "swapfocus.c"
#include "tagall.c"
#include "tagallmon.c"
#include "tagswapmon.c"
#include "vanitygaps.c"
#include "warp.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

